/* eslint-disable */
/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at <a href=\"http://swagger.io\">http://swagger.io</a> or on irc.freenode.net, #swagger.  For this sample, you can use the api key \"special-key\" to test the authorization filters
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Order
 */
export interface Order {
  /**
   *
   * @type {number}
   * @memberof Order
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof Order
   */
  petId?: number;
  /**
   *
   * @type {number}
   * @memberof Order
   */
  quantity?: number;
  /**
   *
   * @type {string}
   * @memberof Order
   */
  shipDate?: string;
  /**
   * Order Status
   * @type {string}
   * @memberof Order
   */
  status?: OrderStatusEnum;
  /**
   *
   * @type {boolean}
   * @memberof Order
   */
  complete?: boolean;
}

export const OrderStatusEnum = {
  placed: 'placed',
  approved: 'approved',
  delivered: 'delivered',
} as const;

export type OrderStatusEnum =
  typeof OrderStatusEnum[keyof typeof OrderStatusEnum];
