/* eslint-disable */
/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at <a href=\"http://swagger.io\">http://swagger.io</a> or on irc.freenode.net, #swagger.  For this sample, you can use the api key \"special-key\" to test the authorization filters
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Category } from './category';
import { Tag } from './tag';

/**
 *
 * @export
 * @interface Pet
 */
export interface Pet {
  /**
   *
   * @type {number}
   * @memberof Pet
   */
  id?: number;
  /**
   *
   * @type {Category}
   * @memberof Pet
   */
  category?: Category;
  /**
   *
   * @type {string}
   * @memberof Pet
   */
  name: string;
  /**
   *
   * @type {Array<string>}
   * @memberof Pet
   */
  photoUrls: Array<string>;
  /**
   *
   * @type {Array<Tag>}
   * @memberof Pet
   */
  tags?: Array<Tag>;
  /**
   * pet status in the store
   * @type {string}
   * @memberof Pet
   */
  status?: PetStatusEnum;
}

export const PetStatusEnum = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const;

export type PetStatusEnum = typeof PetStatusEnum[keyof typeof PetStatusEnum];
